version: '2'

services:
  node-app:
    build: app
    restart: always
    container_name: service_container
  httpd:
    build: httpd-proxy
    restart: always
    ports:
      - 3000:80
    links:
      - node-app
